# version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: xode-mongodb
    ports:
      - "27017:27017"
    volumes:
      - xode-db-data:/data/db
    restart: always

volumes:
  xode-db-data: